//  Copyright (c) 2012, Rob J Meijer
//
//
//Permission is hereby granted, free of charge, to any person or organization
//obtaining a copy of the software and accompanying documentation covered by
//this license (the "Software") to use, reproduce, display, distribute,
//execute, and transmit the Software, and to prepare derivative works of the
//Software, and to permit third-parties to whom the Software is furnished to
//do so, all subject to the following:
//
//The copyright notices in the Software and this entire statement, including
//the above license grant, this restriction and the following disclaimer,
//must be included in all copies of the Software, in whole or in part, and
//all derivative works of the Software, unless such copies or derivative
//works are solely in the form of machine-executable object code generated by
//a source language processor.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//DEALINGS IN THE SOFTWARE.

#ifndef KISSLOG_SYSLOGLOGGER_HPP
#define KISSLOG_SYSLOGLOGGER_HPP
#include <kisslog/facility.hpp>
#include <kisslog/severity.hpp>
#include <kisslog/util.hpp>
#include <kisslog/concurrency.hpp>
#include <syslog.h>
#include <string>

namespace kisslog {
  namespace rawlogger {
    template <typename F,typename G,typename C=char>
    class sysloglogger;
    template <typename F,typename G>
    class sysloglogger<F,G,char> {
        std::basic_string<char> mIdent;
        util::CharUtil<char> charutil;
      public:
        sysloglogger(std::basic_string<char> ident):mIdent(ident),charutil() {
          openlog(mIdent.c_str(),LOG_PID, F::asSyslogFacility());    
        } 
        ~sysloglogger() {
           closelog();
        }

        template <severity::Severity S>
        void log(std::basic_string<char> line) {
           threading::guard_if_needed<G> myguard;
           syslog(S,"%s",(severity::asPrefix<S,char>() + charutil.sp_col_sp() + line).c_str());
        }
    };
  }
}
#endif
