//  Copyright (c) 2012, Rob J Meijer
//
//
//Permission is hereby granted, free of charge, to any person or organization
//obtaining a copy of the software and accompanying documentation covered by
//this license (the "Software") to use, reproduce, display, distribute,
//execute, and transmit the Software, and to prepare derivative works of the
//Software, and to permit third-parties to whom the Software is furnished to
//do so, all subject to the following:
//
//The copyright notices in the Software and this entire statement, including
//the above license grant, this restriction and the following disclaimer,
//must be included in all copies of the Software, in whole or in part, and
//all derivative works of the Software, unless such copies or derivative
//works are solely in the form of machine-executable object code generated by
//a source language processor.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//DEALINGS IN THE SOFTWARE.

#ifndef KISSLOG_UTIL_HPP
#define KISSLOG_UTIL_HPP
#include <string>
#include <ctime>

namespace kisslog {
  namespace util {
    template <typename CharType>    
    struct CharUtil; 
    template <>
    struct CharUtil<char> {
      std::char_traits<char>::int_type newline() { return '\n';}
      std::basic_string<char> sp_col_sp() { return " : "; }
      std::basic_string<char> iso_now() {
          time_t ctt = time(0);
          char mbstr[100];
          std::strftime(mbstr, 100, "%Y-%m-%dT%H:%M:%SZ", std::localtime(&ctt));
          return mbstr;
      };
      std::basic_string<char> now() {
          return this->iso_now();
      }
      size_t max_char_len() {
         return 4;
      }
      bool can_truncate(char *data){ 
         char c2=data[2];
         if ((c2 & 0x80) == 0) {
            return true;
         }
         char c1=data[1];
         if (((c2 & 0xc0) == 0xc0) || ((c1 & 0xe0) == 0xe0)) {
            return false;
         }
         if (((c1 & 0xc0) == 0xc0) || ((c1 & 0x80) == 0)) {
           return true;
         }
         char c0=data[0];
         if ((c0 & 0xf0) == 0xf0) {
           return false;
         }
         return true;
      } 
    };
    template <>
    struct CharUtil<wchar_t> {
     private:
      CharUtil<char> mBaseCharUtil;
     public:
      std::char_traits<wchar_t>::int_type newline() { return L'\n';}
      std::basic_string<wchar_t> sp_col_sp() { return L" : "; }
      size_t max_char_len() {
         return 1;
      }
      bool can_truncate(wchar_t *data){
         return true;
       }
      std::basic_string<wchar_t> iso_now() {
          std::string nowstring=mBaseCharUtil.now();
          std::wstring ws;
          ws.assign(nowstring.begin(), nowstring.end());
          return ws;
       };
      std::basic_string<wchar_t> now() {
          return this->iso_now();
      }
    };
    #if defined(__GXX_EXPERIMENTAL_CXX0X__) || __cplusplus >= 201103L
    template <>
    struct CharUtil<char16_t> {
      private:
       CharUtil<char> mBaseCharUtil;
      public:
       std::char_traits<char16_t>::int_type newline() { return u'\n';}
       std::basic_string<char16_t> sp_col_sp() { return u" : "; }  
       std::basic_string<char16_t> iso_now() {
          std::string nowstring=mBaseCharUtil.now();
          std::basic_string<char16_t> ws;
          ws.assign(nowstring.begin(), nowstring.end());
          return ws;
       };
       std::basic_string<char16_t> now() {
          return this->iso_now();
       }
       size_t max_char_len() {
         return 2;
       }
       bool can_truncate(char16_t *data){
         if ((data[0] & 0xd800) == 0xd800) {
            return false;
         }
         return true;
       }
    };
    template <>
    struct CharUtil<char32_t> {
      private:
       CharUtil<char> mBaseCharUtil;
      public:
       std::char_traits<char32_t>::int_type newline() { return U'\n';}
       std::basic_string<char32_t> sp_col_sp() { return U" : "; }
       std::basic_string<char32_t> iso_now() {
          std::string nowstring=mBaseCharUtil.now();
          std::basic_string<char32_t> ws;
          ws.assign(nowstring.begin(), nowstring.end());
          return ws;
       };
       std::basic_string<char32_t> now() {
          return this->iso_now();
       }
       size_t max_char_len() {
         return 1;
       }
       bool can_truncate(char16_t *data){
         return true;
       }
    };
    #endif
  }
}
#endif
