//  Copyright (c) 2012, Rob J Meijer
//
//
//Permission is hereby granted, free of charge, to any person or organization
//obtaining a copy of the software and accompanying documentation covered by
//this license (the "Software") to use, reproduce, display, distribute,
//execute, and transmit the Software, and to prepare derivative works of the
//Software, and to permit third-parties to whom the Software is furnished to
//do so, all subject to the following:
//
//The copyright notices in the Software and this entire statement, including
//the above license grant, this restriction and the following disclaimer,
//must be included in all copies of the Software, in whole or in part, and
//all derivative works of the Software, unless such copies or derivative
//works are solely in the form of machine-executable object code generated by
//a source language processor.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//DEALINGS IN THE SOFTWARE.

#ifndef KISSLOG_UTIL_HPP
#define KISSLOG_UTIL_HPP
#include <string>
#include <ctime>

namespace kisslog {
  namespace util {
    template <typename CharType>    
    struct CharUtil; 
    template <>
    struct CharUtil<char> {
      std::char_traits<char>::int_type newline() { return '\n';}
      std::basic_string<char> sp_col_sp() { return " : "; }
      std::basic_string<char> iso_now() {
          time_t ctt = time(0);
          char mbstr[100];
          std::strftime(mbstr, 100, "%FT%TZ", std::localtime(&ctt));
          return mbstr;
      };
      std::basic_string<char> now() {
          return this->iso_now();
      }
    };
    template <>
    struct CharUtil<wchar_t> {
      std::char_traits<wchar_t>::int_type newline() { return L'\n';}
      std::basic_string<wchar_t> sp_col_sp() { return L" : "; }
      //FIXME: we need a wchar_t 'now()' definition also!.
    };
  }
}
#endif
